"""Card catalog for the Slovak vocabulary card collection system."""

from typing import TypedDict


class CardDef(TypedDict):
    id: int
    set_id: str
    set_name: str
    set_emoji: str
    emoji: str
    slovak: str
    pronunciation: str
    english: str
    example_sk: str
    example_en: str
    rarity: str  # "common" | "uncommon" | "rare" | "legendary"
    number: int
    origin: str  # "Slovak" | "Pan-Slavic" | "West Slavic" | "East Slavic" | "Czech/Slovak" | "International" | "Hungarian influence"


# Set definitions for pack display
SETS: dict[str, dict] = {
    "myty": {"name": "Mýty a Legendy", "emoji": "🐉", "description": "Myths & Legends", "cost": 150},
    "jedlo": {"name": "Slovenská Kuchyňa", "emoji": "🥟", "description": "Slovak Kitchen", "cost": 150},
    "pamiatky": {"name": "Pamiatky", "emoji": "🏰", "description": "Landmarks", "cost": 150},
    "slang": {"name": "Slang & Výrazy", "emoji": "🗣️", "description": "Slang & Expressions", "cost": 150},
    "rozpravky": {"name": "Rozprávky", "emoji": "🧚", "description": "Fairy Tales", "cost": 150},
    "futbal": {"name": "Futbal", "emoji": "⚽", "description": "Football", "cost": 150},
    "zvierata": {"name": "Tatranská Fauna", "emoji": "🐻", "description": "Tatra Wildlife", "cost": 150},
    "tradicie": {"name": "Tradície", "emoji": "🎭", "description": "Traditions", "cost": 150},
    "priroda": {"name": "Slovenská Príroda", "emoji": "🏔️", "description": "Slovak Nature", "cost": 150},
    "hudba": {"name": "Hudba a Umenie", "emoji": "🎵", "description": "Music & Art", "cost": 150},
}

CARDS: list[CardDef] = [
    # =========================================================================
    # SET 1: Mýty a Legendy (Myths & Legends) 🐉
    # 8 Common, 4 Uncommon, 2 Rare, 1 Legendary
    # =========================================================================
    {
        "id": 1, "set_id": "myty", "set_name": "Mýty a Legendy", "set_emoji": "🐉",
        "emoji": "🧜‍♂️", "slovak": "vodník", "pronunciation": "VOD-neek",
        "english": "water spirit",
        "example_sk": "Vodník žije na dne rybníka a láka neopatrných pocestných.",
        "example_en": "The water spirit lives at the bottom of the pond and lures careless travelers.",
        "rarity": "common", "number": 1, "origin": "Pan-Slavic",
    },
    {
        "id": 2, "set_id": "myty", "set_name": "Mýty a Legendy", "set_emoji": "🐉",
        "emoji": "🧚", "slovak": "víla", "pronunciation": "VEE-lah",
        "english": "fairy / nymph",
        "example_sk": "Víly tancovali na lesnej lúke pri svite mesiaca.",
        "example_en": "The fairies danced in the forest meadow by moonlight.",
        "rarity": "common", "number": 2, "origin": "Pan-Slavic",
    },
    {
        "id": 3, "set_id": "myty", "set_name": "Mýty a Legendy", "set_emoji": "🐉",
        "emoji": "😈", "slovak": "čert", "pronunciation": "CHERT",
        "english": "devil",
        "example_sk": "Čert sa podľa legiend skrýval v opustených baniach.",
        "example_en": "The devil, according to legends, hid in abandoned mines.",
        "rarity": "common", "number": 3, "origin": "Pan-Slavic",
    },
    {
        "id": 4, "set_id": "myty", "set_name": "Mýty a Legendy", "set_emoji": "🐉",
        "emoji": "🐲", "slovak": "drak", "pronunciation": "DRAHK",
        "english": "dragon",
        "example_sk": "Drak strážil poklad ukrytý hlboko v jaskyni.",
        "example_en": "The dragon guarded treasure hidden deep in the cave.",
        "rarity": "common", "number": 4, "origin": "Pan-Slavic",
    },
    {
        "id": 5, "set_id": "myty", "set_name": "Mýty a Legendy", "set_emoji": "🐉",
        "emoji": "🧙‍♀️", "slovak": "ježibaba", "pronunciation": "YEH-zhih-bah-bah",
        "english": "witch in the woods",
        "example_sk": "Ježibaba bývala v chalúpke hlboko v tmavom lese.",
        "example_en": "The forest witch lived in a hut deep in the dark woods.",
        "rarity": "common", "number": 5, "origin": "West Slavic",
    },
    {
        "id": 6, "set_id": "myty", "set_name": "Mýty a Legendy", "set_emoji": "🐉",
        "emoji": "🧛", "slovak": "strigoň", "pronunciation": "STRIH-gohn",
        "english": "vampire",
        "example_sk": "Podľa starých povestí strigoň vychádzal z hrobu o polnoci.",
        "example_en": "According to old tales, the vampire emerged from the grave at midnight.",
        "rarity": "common", "number": 6, "origin": "Slovak",
    },
    {
        "id": 7, "set_id": "myty", "set_name": "Mýty a Legendy", "set_emoji": "🐉",
        "emoji": "🔮", "slovak": "bosorka", "pronunciation": "BOH-sor-kah",
        "english": "witch / sorceress",
        "example_sk": "Bosorka pripravovala tajomné lektvary z lesných bylín.",
        "example_en": "The sorceress brewed mysterious potions from forest herbs.",
        "rarity": "common", "number": 7, "origin": "Slovak",
    },
    {
        "id": 8, "set_id": "myty", "set_name": "Mýty a Legendy", "set_emoji": "🐉",
        "emoji": "🐉", "slovak": "šarkan", "pronunciation": "SHAR-kahn",
        "english": "dragon (Slovak variant)",
        "example_sk": "Šarkan mal podľa slovenských povestí viac hláv.",
        "example_en": "The Slovak dragon had multiple heads according to folk tales.",
        "rarity": "common", "number": 8, "origin": "Slovak",
    },
    {
        "id": 9, "set_id": "myty", "set_name": "Mýty a Legendy", "set_emoji": "🐉",
        "emoji": "😱", "slovak": "mora", "pronunciation": "MOH-rah",
        "english": "nightmare spirit",
        "example_sk": "Mora sadala spiiacim ľuďom na hruď a prinášala zlé sny.",
        "example_en": "The nightmare spirit sat on sleepers' chests and brought bad dreams.",
        "rarity": "uncommon", "number": 9, "origin": "Pan-Slavic",
    },
    {
        "id": 10, "set_id": "myty", "set_name": "Mýty a Legendy", "set_emoji": "🐉",
        "emoji": "✨", "slovak": "svetlonoš", "pronunciation": "SVET-loh-nosh",
        "english": "light-bearer",
        "example_sk": "Svetlonoš sa zjavoval pocestným ako žiariace svetlo v noci.",
        "example_en": "The light-bearer appeared to travelers as a glowing light in the night.",
        "rarity": "uncommon", "number": 10, "origin": "Slovak",
    },
    {
        "id": 11, "set_id": "myty", "set_name": "Mýty a Legendy", "set_emoji": "🐉",
        "emoji": "🕯️", "slovak": "blud", "pronunciation": "BLOOD",
        "english": "will-o'-the-wisp",
        "example_sk": "Blud svetielkoval nad bažinami a zvádzal ľudí z cesty.",
        "example_en": "The will-o'-the-wisp flickered above the marshes and led people astray.",
        "rarity": "uncommon", "number": 11, "origin": "Slovak",
    },
    {
        "id": 12, "set_id": "myty", "set_name": "Mýty a Legendy", "set_emoji": "🐉",
        "emoji": "☀️", "slovak": "poludnica", "pronunciation": "POH-lud-nyih-tsah",
        "english": "noon witch / Lady Midday",
        "example_sk": "Poludnica sa zjavovala na poliach v horúcom poludňajšom slnku.",
        "example_en": "The noon witch appeared in the fields under the hot midday sun.",
        "rarity": "uncommon", "number": 12, "origin": "West Slavic",
    },
    {
        "id": 13, "set_id": "myty", "set_name": "Mýty a Legendy", "set_emoji": "🐉",
        "emoji": "💀", "slovak": "kostlivec", "pronunciation": "KOST-lih-vets",
        "english": "skeleton man",
        "example_sk": "Kostlivec strašil deti v starých rozprávkach o temných lesoch.",
        "example_en": "The skeleton man frightened children in old tales of dark forests.",
        "rarity": "rare", "number": 13, "origin": "Slovak",
    },
    {
        "id": 14, "set_id": "myty", "set_name": "Mýty a Legendy", "set_emoji": "🐉",
        "emoji": "🏚️", "slovak": "Baba Jaga", "pronunciation": "BAH-bah YAH-gah",
        "english": "Baba Yaga",
        "example_sk": "Baba Jaga lietala v mažiari a bývala v chalúpke na kuracích nožkách.",
        "example_en": "Baba Yaga flew in a mortar and lived in a hut on chicken legs.",
        "rarity": "rare", "number": 14, "origin": "East Slavic",
    },
    {
        "id": 15, "set_id": "myty", "set_name": "Mýty a Legendy", "set_emoji": "🐉",
        "emoji": "⚔️", "slovak": "Juraj a drak", "pronunciation": "YOO-rai ah DRAHK",
        "english": "St. George and the Dragon",
        "example_sk": "Svätý Juraj je patrónom Slovenska a podľa legendy zabil draka.",
        "example_en": "St. George is the patron of Slovakia and according to legend slew the dragon.",
        "rarity": "legendary", "number": 15, "origin": "Slovak",
    },

    # =========================================================================
    # SET 2: Slovenská Kuchyňa (Slovak Kitchen) 🥟
    # 8 Common, 4 Uncommon, 2 Rare, 1 Legendary
    # =========================================================================
    {
        "id": 16, "set_id": "jedlo", "set_name": "Slovenská Kuchyňa", "set_emoji": "🥟",
        "emoji": "🥟", "slovak": "halušky", "pronunciation": "HAH-loosh-kih",
        "english": "dumplings",
        "example_sk": "Halušky sa robia z múky a zemiakov.",
        "example_en": "Dumplings are made from flour and potatoes.",
        "rarity": "common", "number": 1, "origin": "Slovak",
    },
    {
        "id": 17, "set_id": "jedlo", "set_name": "Slovenská Kuchyňa", "set_emoji": "🥟",
        "emoji": "🧀", "slovak": "bryndza", "pronunciation": "BRIN-dzah",
        "english": "sheep cheese",
        "example_sk": "Pravá slovenská bryndza sa vyrába z ovčieho mlieka.",
        "example_en": "Authentic Slovak bryndza is made from sheep's milk.",
        "rarity": "common", "number": 2, "origin": "Slovak",
    },
    {
        "id": 18, "set_id": "jedlo", "set_name": "Slovenská Kuchyňa", "set_emoji": "🥟",
        "emoji": "🌭", "slovak": "klobása", "pronunciation": "KLOH-bah-sah",
        "english": "sausage",
        "example_sk": "Na vianočných trhoch si dáme klobásu s horčicou.",
        "example_en": "At the Christmas markets we have sausage with mustard.",
        "rarity": "common", "number": 3, "origin": "Slovak",
    },
    {
        "id": 19, "set_id": "jedlo", "set_name": "Slovenská Kuchyňa", "set_emoji": "🥟",
        "emoji": "🥞", "slovak": "palacinky", "pronunciation": "PAH-lah-tsin-kih",
        "english": "crepes",
        "example_sk": "Palacinky plnené džemom sú obľúbený dezert.",
        "example_en": "Crepes filled with jam are a popular dessert.",
        "rarity": "common", "number": 4, "origin": "Hungarian influence",
    },
    {
        "id": 20, "set_id": "jedlo", "set_name": "Slovenská Kuchyňa", "set_emoji": "🥟",
        "emoji": "🥗", "slovak": "zemiakový šalát", "pronunciation": "ZEH-myah-koh-vee SHAH-laht",
        "english": "potato salad",
        "example_sk": "Zemiakový šalát nesmie chýbať na štedrovečernom stole.",
        "example_en": "Potato salad must not be missing from the Christmas Eve table.",
        "rarity": "common", "number": 5, "origin": "Slovak",
    },
    {
        "id": 21, "set_id": "jedlo", "set_name": "Slovenská Kuchyňa", "set_emoji": "🥟",
        "emoji": "🫀", "slovak": "pečeň", "pronunciation": "PEH-chen",
        "english": "liver",
        "example_sk": "Babička robí výbornú pečeňovú paštétu.",
        "example_en": "Grandma makes an excellent liver pate.",
        "rarity": "common", "number": 6, "origin": "Pan-Slavic",
    },
    {
        "id": 22, "set_id": "jedlo", "set_name": "Slovenská Kuchyňa", "set_emoji": "🥟",
        "emoji": "🍝", "slovak": "šúľance", "pronunciation": "SHOO-lyahn-tseh",
        "english": "sweet noodles",
        "example_sk": "Šúľance s makom a cukrom sú tradičný slovenský dezert.",
        "example_en": "Sweet noodles with poppy seeds and sugar are a traditional Slovak dessert.",
        "rarity": "common", "number": 7, "origin": "Slovak",
    },
    {
        "id": 23, "set_id": "jedlo", "set_name": "Slovenská Kuchyňa", "set_emoji": "🥟",
        "emoji": "🥬", "slovak": "kapusta", "pronunciation": "KAH-poos-tah",
        "english": "cabbage",
        "example_sk": "Kyslá kapusta sa podáva k mnohým slovenským jedlám.",
        "example_en": "Sauerkraut is served alongside many Slovak dishes.",
        "rarity": "common", "number": 8, "origin": "Pan-Slavic",
    },
    {
        "id": 24, "set_id": "jedlo", "set_name": "Slovenská Kuchyňa", "set_emoji": "🥟",
        "emoji": "🧁", "slovak": "trdelník", "pronunciation": "TUR-del-neek",
        "english": "chimney cake",
        "example_sk": "Trdelník sa pečie na valci nad ohňom a posype cukrom.",
        "example_en": "Chimney cake is baked on a cylinder over fire and sprinkled with sugar.",
        "rarity": "uncommon", "number": 9, "origin": "Czech/Slovak",
    },
    {
        "id": 25, "set_id": "jedlo", "set_name": "Slovenská Kuchyňa", "set_emoji": "🥟",
        "emoji": "🫓", "slovak": "lokše", "pronunciation": "LOK-sheh",
        "english": "potato flatbread",
        "example_sk": "Lokše sa robia zo zemiakového cesta a jedia sa s husacím mäsom.",
        "example_en": "Potato flatbread is made from potato dough and eaten with goose meat.",
        "rarity": "uncommon", "number": 10, "origin": "Slovak",
    },
    {
        "id": 26, "set_id": "jedlo", "set_name": "Slovenská Kuchyňa", "set_emoji": "🥟",
        "emoji": "🥟", "slovak": "pirohy", "pronunciation": "PIH-roh-hee",
        "english": "pierogi",
        "example_sk": "Pirohy plnené bryndzou sú obľúbené na východnom Slovensku.",
        "example_en": "Pierogi filled with bryndza cheese are popular in eastern Slovakia.",
        "rarity": "uncommon", "number": 11, "origin": "Pan-Slavic",
    },
    {
        "id": 27, "set_id": "jedlo", "set_name": "Slovenská Kuchyňa", "set_emoji": "🥟",
        "emoji": "🥃", "slovak": "pálenka", "pronunciation": "PAH-len-kah",
        "english": "fruit brandy",
        "example_sk": "Domáca slivovica je najznámejšia slovenská pálenka.",
        "example_en": "Homemade plum brandy is the most famous Slovak spirit.",
        "rarity": "uncommon", "number": 12, "origin": "Slovak",
    },
    {
        "id": 28, "set_id": "jedlo", "set_name": "Slovenská Kuchyňa", "set_emoji": "🥟",
        "emoji": "🫕", "slovak": "kapustnica", "pronunciation": "KAH-poost-nyih-tsah",
        "english": "Christmas cabbage soup",
        "example_sk": "Kapustnica je tradičná vianočná polievka s hubami a klobásou.",
        "example_en": "Cabbage soup is a traditional Christmas soup with mushrooms and sausage.",
        "rarity": "rare", "number": 13, "origin": "Slovak",
    },
    {
        "id": 29, "set_id": "jedlo", "set_name": "Slovenská Kuchyňa", "set_emoji": "🥟",
        "emoji": "🍲", "slovak": "šošovicová polievka", "pronunciation": "SHOH-shoh-vit-soh-vah POH-lyev-kah",
        "english": "lentil soup (New Year's)",
        "example_sk": "Na Nový rok sa je šošovicová polievka, aby bol rok bohatý.",
        "example_en": "Lentil soup is eaten on New Year's Day so the year will be prosperous.",
        "rarity": "rare", "number": 14, "origin": "Slovak",
    },
    {
        "id": 30, "set_id": "jedlo", "set_name": "Slovenská Kuchyňa", "set_emoji": "🥟",
        "emoji": "🇸🇰", "slovak": "bryndzové halušky", "pronunciation": "BRIN-dzoh-veh HAH-loosh-kih",
        "english": "potato dumplings with sheep cheese",
        "example_sk": "Bryndzové halušky sú národné jedlo Slovenska a symbol slovenskej kuchyne.",
        "example_en": "Bryndzove halusky is the national dish of Slovakia and a symbol of Slovak cuisine.",
        "rarity": "legendary", "number": 15, "origin": "Slovak",
    },

    # =========================================================================
    # SET 3: Pamiatky (Landmarks) 🏰
    # 8 Common, 4 Uncommon, 2 Rare, 1 Legendary
    # =========================================================================
    {
        "id": 31, "set_id": "pamiatky", "set_name": "Pamiatky", "set_emoji": "🏰",
        "emoji": "🏰", "slovak": "Bratislavský hrad", "pronunciation": "BRAH-tih-slav-skee HRAHD",
        "english": "Bratislava Castle",
        "example_sk": "Bratislavský hrad sa týči nad Dunajom a je symbolom hlavného mesta.",
        "example_en": "Bratislava Castle towers above the Danube and is the symbol of the capital.",
        "rarity": "common", "number": 1, "origin": "Slovak",
    },
    {
        "id": 32, "set_id": "pamiatky", "set_name": "Pamiatky", "set_emoji": "🏰",
        "emoji": "🌊", "slovak": "Dunaj", "pronunciation": "DOO-nai",
        "english": "Danube river",
        "example_sk": "Dunaj preteká cez Bratislavu a spája viaceré európske krajiny.",
        "example_en": "The Danube flows through Bratislava and connects several European countries.",
        "rarity": "common", "number": 2, "origin": "Slovak",
    },
    {
        "id": 33, "set_id": "pamiatky", "set_name": "Pamiatky", "set_emoji": "🏰",
        "emoji": "⛲", "slovak": "Hlavné námestie", "pronunciation": "HLAHV-neh NAH-myes-tyeh",
        "english": "Main Square, Bratislava",
        "example_sk": "Na Hlavnom námestí v Bratislave sa konajú vianočné trhy.",
        "example_en": "Christmas markets take place on the Main Square in Bratislava.",
        "rarity": "common", "number": 3, "origin": "Slovak",
    },
    {
        "id": 34, "set_id": "pamiatky", "set_name": "Pamiatky", "set_emoji": "🏰",
        "emoji": "🏔️", "slovak": "Starý Smokovec", "pronunciation": "STAH-ree SMOH-koh-vets",
        "english": "Stary Smokovec (Tatra resort town)",
        "example_sk": "Starý Smokovec je obľúbené východisko na túry do Vysokých Tatier.",
        "example_en": "Stary Smokovec is a popular starting point for hikes into the High Tatras.",
        "rarity": "common", "number": 4, "origin": "Slovak",
    },
    {
        "id": 35, "set_id": "pamiatky", "set_name": "Pamiatky", "set_emoji": "🏰",
        "emoji": "🕳️", "slovak": "Demänovská jaskyňa", "pronunciation": "DEH-mä-nov-skah YAHS-kih-nyah",
        "english": "Demanovska Cave",
        "example_sk": "Demänovská jaskyňa slobody patrí medzi najkrajšie jaskyne v Európe.",
        "example_en": "Demanovska Cave of Liberty is among the most beautiful caves in Europe.",
        "rarity": "common", "number": 5, "origin": "Slovak",
    },
    {
        "id": 36, "set_id": "pamiatky", "set_name": "Pamiatky", "set_emoji": "🏰",
        "emoji": "💎", "slovak": "Štrbské pleso", "pronunciation": "SHTRB-skeh PLEH-soh",
        "english": "Strbske Pleso (mountain lake)",
        "example_sk": "Štrbské pleso je krásne horské jazero vo Vysokých Tatrách.",
        "example_en": "Strbske Pleso is a beautiful mountain lake in the High Tatras.",
        "rarity": "common", "number": 6, "origin": "Slovak",
    },
    {
        "id": 37, "set_id": "pamiatky", "set_name": "Pamiatky", "set_emoji": "🏰",
        "emoji": "🏯", "slovak": "Devín", "pronunciation": "DEH-veen",
        "english": "Devin Castle",
        "example_sk": "Hrad Devín stojí na sútoku Dunaja a Moravy.",
        "example_en": "Devin Castle stands at the confluence of the Danube and the Morava rivers.",
        "rarity": "common", "number": 7, "origin": "Slovak",
    },
    {
        "id": 38, "set_id": "pamiatky", "set_name": "Pamiatky", "set_emoji": "🏰",
        "emoji": "🏘️", "slovak": "Vlkolínec", "pronunciation": "VUL-koh-lee-nets",
        "english": "Vlkolinec (UNESCO village)",
        "example_sk": "Vlkolínec je zachovaná ľudová dedina zapísaná v UNESCO.",
        "example_en": "Vlkolinec is a preserved folk village listed by UNESCO.",
        "rarity": "common", "number": 8, "origin": "Slovak",
    },
    {
        "id": 39, "set_id": "pamiatky", "set_name": "Pamiatky", "set_emoji": "🏰",
        "emoji": "🏰", "slovak": "Spišský hrad", "pronunciation": "SPISH-skee HRAHD",
        "english": "Spis Castle",
        "example_sk": "Spišský hrad je jeden z najväčších hradov v Európe.",
        "example_en": "Spis Castle is one of the largest castles in Europe.",
        "rarity": "uncommon", "number": 9, "origin": "Slovak",
    },
    {
        "id": 40, "set_id": "pamiatky", "set_name": "Pamiatky", "set_emoji": "🏰",
        "emoji": "🏛️", "slovak": "Bardejov", "pronunciation": "BAHR-deh-yov",
        "english": "Bardejov (UNESCO town)",
        "example_sk": "Bardejov má jedno z najlepšie zachovaných stredovekých námestí v Európe.",
        "example_en": "Bardejov has one of the best-preserved medieval squares in Europe.",
        "rarity": "uncommon", "number": 10, "origin": "Slovak",
    },
    {
        "id": 41, "set_id": "pamiatky", "set_name": "Pamiatky", "set_emoji": "🏰",
        "emoji": "🦇", "slovak": "Oravský hrad", "pronunciation": "OH-rav-skee HRAHD",
        "english": "Orava Castle",
        "example_sk": "Na Oravskom hrade sa nakrúcal film Nosferatu.",
        "example_en": "The film Nosferatu was shot at Orava Castle.",
        "rarity": "uncommon", "number": 11, "origin": "Slovak",
    },
    {
        "id": 42, "set_id": "pamiatky", "set_name": "Pamiatky", "set_emoji": "🏰",
        "emoji": "⛏️", "slovak": "Banská Štiavnica", "pronunciation": "BAHN-skah SHTYAHV-nyih-tsah",
        "english": "Banska Stiavnica (mining town)",
        "example_sk": "Banská Štiavnica bola kedysi najbohatším banským mestom v Uhorsku.",
        "example_en": "Banska Stiavnica was once the richest mining town in the Kingdom of Hungary.",
        "rarity": "uncommon", "number": 12, "origin": "Slovak",
    },
    {
        "id": 43, "set_id": "pamiatky", "set_name": "Pamiatky", "set_emoji": "🏰",
        "emoji": "🗻", "slovak": "Lomnický štít", "pronunciation": "LOM-nits-kee SHTEET",
        "english": "Lomnicky Peak",
        "example_sk": "Na Lomnický štít sa dostanete lanovkou a z vrchu vidíte celé Tatry.",
        "example_en": "You can reach Lomnicky Peak by cable car and see the entire Tatras from the top.",
        "rarity": "rare", "number": 13, "origin": "Slovak",
    },
    {
        "id": 44, "set_id": "pamiatky", "set_name": "Pamiatky", "set_emoji": "🏰",
        "emoji": "🏰", "slovak": "Bojnický zámok", "pronunciation": "BOY-nyits-kee ZAH-mok",
        "english": "Bojnice Castle",
        "example_sk": "Bojnický zámok vyzerá ako z rozprávky a je najnavštevovanejší na Slovensku.",
        "example_en": "Bojnice Castle looks like something from a fairy tale and is the most visited in Slovakia.",
        "rarity": "rare", "number": 14, "origin": "Slovak",
    },
    {
        "id": 45, "set_id": "pamiatky", "set_name": "Pamiatky", "set_emoji": "🏰",
        "emoji": "⛪", "slovak": "Dóm svätej Alžbety", "pronunciation": "DOHM SVAH-tay AHL-zhbeh-tih",
        "english": "St. Elizabeth's Cathedral, Kosice",
        "example_sk": "Dóm svätej Alžbety v Košiciach je najväčší gotický kostol na Slovensku.",
        "example_en": "St. Elizabeth's Cathedral in Kosice is the largest Gothic church in Slovakia.",
        "rarity": "legendary", "number": 15, "origin": "Slovak",
    },

    # =========================================================================
    # SET 4: Slang & Výrazy (Slang & Expressions) 🗣️
    # 8 Common, 4 Uncommon, 2 Rare, 1 Legendary
    # =========================================================================
    {
        "id": 46, "set_id": "slang", "set_name": "Slang & Výrazy", "set_emoji": "🗣️",
        "emoji": "👋", "slovak": "Ahoj", "pronunciation": "AH-hoy",
        "english": "hi / bye",
        "example_sk": "Ahoj, ako sa máš? Dávno sme sa nevideli!",
        "example_en": "Hi, how are you? We haven't seen each other in a long time!",
        "rarity": "common", "number": 1, "origin": "International",
    },
    {
        "id": 47, "set_id": "slang", "set_name": "Slang & Výrazy", "set_emoji": "🗣️",
        "emoji": "✌️", "slovak": "Čau", "pronunciation": "CHOW",
        "english": "bye (casual)",
        "example_sk": "Čau, uvidíme sa zajtra!",
        "example_en": "Bye, see you tomorrow!",
        "rarity": "common", "number": 2, "origin": "International",
    },
    {
        "id": 48, "set_id": "slang", "set_name": "Slang & Výrazy", "set_emoji": "🗣️",
        "emoji": "😎", "slovak": "Pohoda", "pronunciation": "POH-hoh-dah",
        "english": "chill / fine / no worries",
        "example_sk": "Ako bolo na výlete? — Pohoda, bolo super.",
        "example_en": "How was the trip? — Chill, it was great.",
        "rarity": "common", "number": 3, "origin": "Slovak",
    },
    {
        "id": 49, "set_id": "slang", "set_name": "Slang & Výrazy", "set_emoji": "🗣️",
        "emoji": "👍", "slovak": "Dobre", "pronunciation": "DOB-reh",
        "english": "good / ok",
        "example_sk": "Stretneme sa o piatej. — Dobre, budem tam.",
        "example_en": "We'll meet at five. — OK, I'll be there.",
        "rarity": "common", "number": 4, "origin": "Pan-Slavic",
    },
    {
        "id": 50, "set_id": "slang", "set_name": "Slang & Výrazy", "set_emoji": "🗣️",
        "emoji": "🤌", "slovak": "Fajn", "pronunciation": "FINE",
        "english": "fine (borrowed word)",
        "example_sk": "Ako sa cítiš? — Fajn, ďakujem.",
        "example_en": "How are you feeling? — Fine, thanks.",
        "rarity": "common", "number": 5, "origin": "International",
    },
    {
        "id": 51, "set_id": "slang", "set_name": "Slang & Výrazy", "set_emoji": "🗣️",
        "emoji": "💡", "slovak": "Jasné", "pronunciation": "YAHS-neh",
        "english": "sure / clear",
        "example_sk": "Môžeš mi pomôcť? — Jasné, žiadny problém.",
        "example_en": "Can you help me? — Sure, no problem.",
        "rarity": "common", "number": 6, "origin": "Pan-Slavic",
    },
    {
        "id": 52, "set_id": "slang", "set_name": "Slang & Výrazy", "set_emoji": "🗣️",
        "emoji": "🌟", "slovak": "Super", "pronunciation": "SOO-per",
        "english": "great",
        "example_sk": "Dostal som jednotku zo skúšky! — Super, gratulujem!",
        "example_en": "I got an A on the exam! — Great, congratulations!",
        "rarity": "common", "number": 7, "origin": "International",
    },
    {
        "id": 53, "set_id": "slang", "set_name": "Slang & Výrazy", "set_emoji": "🗣️",
        "emoji": "🎉", "slovak": "Paráda", "pronunciation": "PAH-rah-dah",
        "english": "awesome",
        "example_sk": "Vyhrali sme zápas! — Paráda!",
        "example_en": "We won the match! — Awesome!",
        "rarity": "common", "number": 8, "origin": "Slovak",
    },
    {
        "id": 54, "set_id": "slang", "set_name": "Slang & Výrazy", "set_emoji": "🗣️",
        "emoji": "🧈", "slovak": "Mať maslo na hlave", "pronunciation": "MAHTY MAHS-loh NAH HLAH-veh",
        "english": "to have butter on one's head (= guilty conscience)",
        "example_sk": "Nekritizuj iných, veď sám máš maslo na hlave.",
        "example_en": "Don't criticize others when you yourself have a guilty conscience. (Lit: butter on your head)",
        "rarity": "uncommon", "number": 9, "origin": "Slovak",
    },
    {
        "id": 55, "set_id": "slang", "set_name": "Slang & Výrazy", "set_emoji": "🗣️",
        "emoji": "😵", "slovak": "Padnúť na nos", "pronunciation": "PAHD-noot NAH NOS",
        "english": "to fall on your nose (= to fail)",
        "example_sk": "S tým projektom úplne padol na nos.",
        "example_en": "He totally failed with that project. (Lit: fell on his nose)",
        "rarity": "uncommon", "number": 10, "origin": "Slovak",
    },
    {
        "id": 56, "set_id": "slang", "set_name": "Slang & Výrazy", "set_emoji": "🗣️",
        "emoji": "🔨", "slovak": "Trafiť klinec po hlavičke", "pronunciation": "TRAH-fity KLIH-nets POH HLAH-vich-keh",
        "english": "hit the nail on the head",
        "example_sk": "Tvojou odpoveďou si trafil klinec po hlavičke.",
        "example_en": "With your answer, you hit the nail on the head.",
        "rarity": "uncommon", "number": 11, "origin": "Slovak",
    },
    {
        "id": 57, "set_id": "slang", "set_name": "Slang & Výrazy", "set_emoji": "🗣️",
        "emoji": "🌧️", "slovak": "Liať ako z krhly", "pronunciation": "LYAHTY AH-koh Z KUR-hlih",
        "english": "to pour like from a jug (= raining hard)",
        "example_sk": "Vonku leje ako z krhly, zostaňme doma.",
        "example_en": "It's pouring outside (like from a jug), let's stay home.",
        "rarity": "uncommon", "number": 12, "origin": "Slovak",
    },
    {
        "id": 58, "set_id": "slang", "set_name": "Slang & Výrazy", "set_emoji": "🗣️",
        "emoji": "📏", "slovak": "Ťahať za kratší koniec", "pronunciation": "TYAH-haty ZAH KRAHT-shee KOH-nyets",
        "english": "to pull the shorter end (= get the short end of the stick)",
        "example_sk": "Pri tom obchode som ťahal za kratší koniec.",
        "example_en": "I got the short end of the stick in that deal. (Lit: pulled the shorter end)",
        "rarity": "rare", "number": 13, "origin": "Slovak",
    },
    {
        "id": 59, "set_id": "slang", "set_name": "Slang & Výrazy", "set_emoji": "🗣️",
        "emoji": "💪", "slovak": "Mať guráž", "pronunciation": "MAHTY GOO-rahzh",
        "english": "to have courage (from French)",
        "example_sk": "Treba mať guráž a povedať pravdu.",
        "example_en": "You need to have courage and tell the truth.",
        "rarity": "rare", "number": 14, "origin": "International",
    },
    {
        "id": 60, "set_id": "slang", "set_name": "Slang & Výrazy", "set_emoji": "🗣️",
        "emoji": "📖", "slovak": "Kde bolo, tam bolo...", "pronunciation": "GDEH BOH-loh TAHM BOH-loh",
        "english": "Once upon a time... (Slovak fairy tale opener)",
        "example_sk": "Kde bolo, tam bolo, za siedmimi horami a siedmimi dolinami...",
        "example_en": "Once upon a time, beyond seven mountains and seven valleys...",
        "rarity": "legendary", "number": 15, "origin": "Slovak",
    },

    # =========================================================================
    # SET 5: Rozprávky (Fairy Tales) 🧚
    # 8 Common, 4 Uncommon, 2 Rare, 1 Legendary
    # =========================================================================
    {
        "id": 61, "set_id": "rozpravky", "set_name": "Rozprávky", "set_emoji": "🧚",
        "emoji": "👸", "slovak": "princezná", "pronunciation": "PRIN-tsez-nah",
        "english": "princess",
        "example_sk": "Princezná bola zakliatá v kamennom zámku.",
        "example_en": "The princess was enchanted in a stone castle.",
        "rarity": "common", "number": 1, "origin": "Pan-Slavic",
    },
    {
        "id": 62, "set_id": "rozpravky", "set_name": "Rozprávky", "set_emoji": "🧚",
        "emoji": "🤴", "slovak": "princ", "pronunciation": "PRINTS",
        "english": "prince",
        "example_sk": "Princ sa vydal na dlhú cestu, aby zachránil princeznu.",
        "example_en": "The prince set out on a long journey to save the princess.",
        "rarity": "common", "number": 2, "origin": "Pan-Slavic",
    },
    {
        "id": 63, "set_id": "rozpravky", "set_name": "Rozprávky", "set_emoji": "🧚",
        "emoji": "👑", "slovak": "kráľ", "pronunciation": "KRAHLY",
        "english": "king",
        "example_sk": "Kráľ vládol múdro a spravodlivo celej krajine.",
        "example_en": "The king ruled wisely and justly over the whole land.",
        "rarity": "common", "number": 3, "origin": "Pan-Slavic",
    },
    {
        "id": 64, "set_id": "rozpravky", "set_name": "Rozprávky", "set_emoji": "🧚",
        "emoji": "👸", "slovak": "kráľovná", "pronunciation": "KRAH-lyov-nah",
        "english": "queen",
        "example_sk": "Kráľovná sedela na zlatom tróne v najvyššej veži.",
        "example_en": "The queen sat on a golden throne in the highest tower.",
        "rarity": "common", "number": 4, "origin": "Pan-Slavic",
    },
    {
        "id": 65, "set_id": "rozpravky", "set_name": "Rozprávky", "set_emoji": "🧚",
        "emoji": "🧙", "slovak": "čarodejník", "pronunciation": "CHAH-roh-dey-neek",
        "english": "wizard",
        "example_sk": "Čarodejník premenil princa na žabu jedným kúzlom.",
        "example_en": "The wizard turned the prince into a frog with a single spell.",
        "rarity": "common", "number": 5, "origin": "Pan-Slavic",
    },
    {
        "id": 66, "set_id": "rozpravky", "set_name": "Rozprávky", "set_emoji": "🧚",
        "emoji": "🪄", "slovak": "zakliata", "pronunciation": "ZAH-klyah-tah",
        "english": "enchanted",
        "example_sk": "Zakliata krajina čakala na hrdinu, ktorý zlomí kliatbu.",
        "example_en": "The enchanted land awaited a hero who would break the curse.",
        "rarity": "common", "number": 6, "origin": "Pan-Slavic",
    },
    {
        "id": 67, "set_id": "rozpravky", "set_name": "Rozprávky", "set_emoji": "🧚",
        "emoji": "🏰", "slovak": "zámok", "pronunciation": "ZAH-mok",
        "english": "castle",
        "example_sk": "Za veľkým lesom stál zámok so sto komnatami.",
        "example_en": "Behind the great forest stood a castle with a hundred chambers.",
        "rarity": "common", "number": 7, "origin": "Pan-Slavic",
    },
    {
        "id": 68, "set_id": "rozpravky", "set_name": "Rozprávky", "set_emoji": "🧚",
        "emoji": "👻", "slovak": "duch", "pronunciation": "DOOKH",
        "english": "ghost / spirit",
        "example_sk": "V starom zámku straší duch bieleho rytiera.",
        "example_en": "The ghost of the white knight haunts the old castle.",
        "rarity": "common", "number": 8, "origin": "Pan-Slavic",
    },
    {
        "id": 69, "set_id": "rozpravky", "set_name": "Rozprávky", "set_emoji": "🧚",
        "emoji": "💧", "slovak": "živá voda", "pronunciation": "ZHIH-vah VOH-dah",
        "english": "living water",
        "example_sk": "Živá voda dokázala uzdraviť každú ranu a oživiť mŕtveho.",
        "example_en": "The living water could heal any wound and bring the dead back to life.",
        "rarity": "uncommon", "number": 9, "origin": "Pan-Slavic",
    },
    {
        "id": 70, "set_id": "rozpravky", "set_name": "Rozprávky", "set_emoji": "🧚",
        "emoji": "🔑", "slovak": "zlatý kľúčik", "pronunciation": "ZLAH-tee KLYOO-chik",
        "english": "golden key",
        "example_sk": "Zlatý kľúčik otvoril bránu do zakliateho kráľovstva.",
        "example_en": "The golden key opened the gate to the enchanted kingdom.",
        "rarity": "uncommon", "number": 10, "origin": "Pan-Slavic",
    },
    {
        "id": 71, "set_id": "rozpravky", "set_name": "Rozprávky", "set_emoji": "🧚",
        "emoji": "🏔️", "slovak": "sklenená hora", "pronunciation": "SKLEH-neh-nah HOH-rah",
        "english": "glass mountain",
        "example_sk": "Na sklenenej hore bola princezná a nikto na ňu nedokázal vyliezť.",
        "example_en": "The princess was on the glass mountain and nobody could climb it.",
        "rarity": "uncommon", "number": 11, "origin": "Pan-Slavic",
    },
    {
        "id": 72, "set_id": "rozpravky", "set_name": "Rozprávky", "set_emoji": "🧚",
        "emoji": "🪄", "slovak": "tri prúty", "pronunciation": "TRIH PROO-tih",
        "english": "three wands / rods",
        "example_sk": "Tri prúty mali čarovnú moc a splnili tri priania.",
        "example_en": "The three wands had magical power and granted three wishes.",
        "rarity": "uncommon", "number": 12, "origin": "Slovak",
    },
    {
        "id": 73, "set_id": "rozpravky", "set_name": "Rozprávky", "set_emoji": "🧚",
        "emoji": "👠", "slovak": "Popoluška", "pronunciation": "POH-poh-loosh-kah",
        "english": "Cinderella (Slovak version)",
        "example_sk": "Slovenská Popoluška stratila črievičku na kráľovskom plese.",
        "example_en": "The Slovak Cinderella lost her slipper at the royal ball.",
        "rarity": "rare", "number": 13, "origin": "Pan-Slavic",
    },
    {
        "id": 74, "set_id": "rozpravky", "set_name": "Rozprávky", "set_emoji": "🧚",
        "emoji": "🗓️", "slovak": "Dvanásť mesiačikov", "pronunciation": "DVAH-nahsty MEH-syah-chih-kov",
        "english": "The Twelve Months (classic Slovak tale)",
        "example_sk": "Dvanásť mesiačikov je obľúbená slovenská rozprávka o dobrote a chamtivosti.",
        "example_en": "The Twelve Months is a beloved Slovak fairy tale about kindness and greed.",
        "rarity": "rare", "number": 14, "origin": "Slovak",
    },
    {
        "id": 75, "set_id": "rozpravky", "set_name": "Rozprávky", "set_emoji": "🧚",
        "emoji": "🦅", "slovak": "Jánošík", "pronunciation": "YAH-noh-sheek",
        "english": "Janosik (the Slovak Robin Hood)",
        "example_sk": "Jánošík bral bohatým a dával chudobným — je najslávnejší slovenský hrdina.",
        "example_en": "Janosik took from the rich and gave to the poor — he is Slovakia's most famous folk hero.",
        "rarity": "legendary", "number": 15, "origin": "Slovak",
    },

    # =========================================================================
    # SET 6: Futbal (Football) ⚽
    # 8 Common, 4 Uncommon, 2 Rare, 1 Legendary
    # =========================================================================
    {
        "id": 76, "set_id": "futbal", "set_name": "Futbal", "set_emoji": "⚽",
        "emoji": "⚽", "slovak": "gól", "pronunciation": "GOHL",
        "english": "goal",
        "example_sk": "Dal gól v poslednej minúte zápasu!",
        "example_en": "He scored a goal in the last minute of the match!",
        "rarity": "common", "number": 1, "origin": "International",
    },
    {
        "id": 77, "set_id": "futbal", "set_name": "Futbal", "set_emoji": "⚽",
        "emoji": "🏐", "slovak": "lopta", "pronunciation": "LOP-tah",
        "english": "ball",
        "example_sk": "Podaj mi loptu, chcem strieľať na bránu.",
        "example_en": "Pass me the ball, I want to shoot at the goal.",
        "rarity": "common", "number": 2, "origin": "Pan-Slavic",
    },
    {
        "id": 78, "set_id": "futbal", "set_name": "Futbal", "set_emoji": "⚽",
        "emoji": "🏟️", "slovak": "ihrisko", "pronunciation": "IH-hris-koh",
        "english": "pitch / field",
        "example_sk": "Hráči vybehli na ihrisko pred plným štadiónom.",
        "example_en": "The players ran onto the pitch in front of a full stadium.",
        "rarity": "common", "number": 3, "origin": "Pan-Slavic",
    },
    {
        "id": 79, "set_id": "futbal", "set_name": "Futbal", "set_emoji": "⚽",
        "emoji": "👨‍⚖️", "slovak": "rozhodca", "pronunciation": "ROZ-hod-tsah",
        "english": "referee",
        "example_sk": "Rozhodca odpískal penaltu za faul v pokutovom území.",
        "example_en": "The referee called a penalty for a foul in the box.",
        "rarity": "common", "number": 4, "origin": "Pan-Slavic",
    },
    {
        "id": 80, "set_id": "futbal", "set_name": "Futbal", "set_emoji": "⚽",
        "emoji": "🤼", "slovak": "zápas", "pronunciation": "ZAH-pahs",
        "english": "match",
        "example_sk": "Dnes večer je veľký zápas Slovenska proti Česku.",
        "example_en": "Tonight there's a big match, Slovakia versus Czechia.",
        "rarity": "common", "number": 5, "origin": "Pan-Slavic",
    },
    {
        "id": 81, "set_id": "futbal", "set_name": "Futbal", "set_emoji": "⚽",
        "emoji": "🥅", "slovak": "brána", "pronunciation": "BRAH-nah",
        "english": "goal (goalpost / gate)",
        "example_sk": "Lopta skončila v bráne po krásnej strele z diaľky.",
        "example_en": "The ball ended up in the goal after a beautiful long-range shot.",
        "rarity": "common", "number": 6, "origin": "Pan-Slavic",
    },
    {
        "id": 82, "set_id": "futbal", "set_name": "Futbal", "set_emoji": "⚽",
        "emoji": "🧤", "slovak": "brankár", "pronunciation": "BRAHN-kahr",
        "english": "goalkeeper",
        "example_sk": "Brankár chytil penaltu a zachránil tím.",
        "example_en": "The goalkeeper saved the penalty and rescued the team.",
        "rarity": "common", "number": 7, "origin": "Pan-Slavic",
    },
    {
        "id": 83, "set_id": "futbal", "set_name": "Futbal", "set_emoji": "⚽",
        "emoji": "👥", "slovak": "tím", "pronunciation": "TEEM",
        "english": "team",
        "example_sk": "Celý tím oslavoval víťazstvo v šatni.",
        "example_en": "The whole team celebrated the victory in the dressing room.",
        "rarity": "common", "number": 8, "origin": "International",
    },
    {
        "id": 84, "set_id": "futbal", "set_name": "Futbal", "set_emoji": "⚽",
        "emoji": "🎯", "slovak": "penalta", "pronunciation": "PEH-nahl-tah",
        "english": "penalty",
        "example_sk": "V rozstrele sme premenili všetky penalty.",
        "example_en": "In the shootout we converted all the penalties.",
        "rarity": "uncommon", "number": 9, "origin": "International",
    },
    {
        "id": 85, "set_id": "futbal", "set_name": "Futbal", "set_emoji": "⚽",
        "emoji": "🚩", "slovak": "ofsajd", "pronunciation": "OF-said",
        "english": "offside",
        "example_sk": "Gól neplatil, pretože útočník bol v ofsajde.",
        "example_en": "The goal was disallowed because the striker was offside.",
        "rarity": "uncommon", "number": 10, "origin": "International",
    },
    {
        "id": 86, "set_id": "futbal", "set_name": "Futbal", "set_emoji": "⚽",
        "emoji": "🟨", "slovak": "žltá karta", "pronunciation": "ZHUL-tah KAHR-tah",
        "english": "yellow card",
        "example_sk": "Dostal žltú kartu za tvrdý zákrok.",
        "example_en": "He received a yellow card for a hard tackle.",
        "rarity": "uncommon", "number": 11, "origin": "International",
    },
    {
        "id": 87, "set_id": "futbal", "set_name": "Futbal", "set_emoji": "⚽",
        "emoji": "🟥", "slovak": "červená karta", "pronunciation": "CHER-veh-nah KAHR-tah",
        "english": "red card",
        "example_sk": "Po červenej karte musel hráč opustiť ihrisko.",
        "example_en": "After the red card the player had to leave the pitch.",
        "rarity": "uncommon", "number": 12, "origin": "International",
    },
    {
        "id": 88, "set_id": "futbal", "set_name": "Futbal", "set_emoji": "⚽",
        "emoji": "🌟", "slovak": "Marek Hamšík", "pronunciation": "MAH-rek HAHM-sheek",
        "english": "Marek Hamsik (Slovak football legend)",
        "example_sk": "Marek Hamšík je najlepší slovenský futbalista v histórii s rekordným počtom gólov.",
        "example_en": "Marek Hamsik is the greatest Slovak footballer in history with a record number of goals.",
        "rarity": "rare", "number": 13, "origin": "Slovak",
    },
    {
        "id": 89, "set_id": "futbal", "set_name": "Futbal", "set_emoji": "⚽",
        "emoji": "🏆", "slovak": "Fortuna Liga", "pronunciation": "FOR-too-nah LEE-gah",
        "english": "Fortuna Liga (Slovak top division)",
        "example_sk": "Fortuna Liga je najvyššia futbalová súťaž na Slovensku.",
        "example_en": "Fortuna Liga is the highest football competition in Slovakia.",
        "rarity": "rare", "number": 14, "origin": "Slovak",
    },
    {
        "id": 90, "set_id": "futbal", "set_name": "Futbal", "set_emoji": "⚽",
        "emoji": "🇸🇰", "slovak": "Slovensko na MS 2010", "pronunciation": "SLOH-ven-skoh NAH EM-ES DVAH-tih-syahts-deh-syahty",
        "english": "Slovakia at 2010 World Cup",
        "example_sk": "Na MS 2010 Slovensko porazilo Taliansko 3:2 a postúpilo zo skupiny!",
        "example_en": "At the 2010 World Cup Slovakia beat Italy 3-2 and advanced from the group!",
        "rarity": "legendary", "number": 15, "origin": "Slovak",
    },

    # =========================================================================
    # SET 7: Tatranská Fauna (Tatra Wildlife) 🐻
    # 8 Common, 4 Uncommon, 2 Rare, 1 Legendary
    # =========================================================================
    {
        "id": 91, "set_id": "zvierata", "set_name": "Tatranská Fauna", "set_emoji": "🐻",
        "emoji": "🐻", "slovak": "medveď", "pronunciation": "MED-vedy",
        "english": "bear",
        "example_sk": "V slovenských horách žije niekoľko stoviek medveďov hnedých.",
        "example_en": "Several hundred brown bears live in the Slovak mountains.",
        "rarity": "common", "number": 1, "origin": "Pan-Slavic",
    },
    {
        "id": 92, "set_id": "zvierata", "set_name": "Tatranská Fauna", "set_emoji": "🐻",
        "emoji": "🐺", "slovak": "vlk", "pronunciation": "VULK",
        "english": "wolf",
        "example_sk": "Vlk vyje na mesiac v hlbokých karpatských lesoch.",
        "example_en": "The wolf howls at the moon in the deep Carpathian forests.",
        "rarity": "common", "number": 2, "origin": "Pan-Slavic",
    },
    {
        "id": 93, "set_id": "zvierata", "set_name": "Tatranská Fauna", "set_emoji": "🐻",
        "emoji": "🦌", "slovak": "jeleň", "pronunciation": "YEH-len",
        "english": "deer",
        "example_sk": "Na jeseň môžete počuť jeleňa, ako ručí v lesoch Tatier.",
        "example_en": "In autumn you can hear deer roaring in the Tatra forests.",
        "rarity": "common", "number": 3, "origin": "Pan-Slavic",
    },
    {
        "id": 94, "set_id": "zvierata", "set_name": "Tatranská Fauna", "set_emoji": "🐻",
        "emoji": "🦊", "slovak": "líška", "pronunciation": "LEESH-kah",
        "english": "fox",
        "example_sk": "Líška sa šikovne skrýva v podhorských lesoch.",
        "example_en": "The fox cleverly hides in the foothill forests.",
        "rarity": "common", "number": 4, "origin": "Pan-Slavic",
    },
    {
        "id": 95, "set_id": "zvierata", "set_name": "Tatranská Fauna", "set_emoji": "🐻",
        "emoji": "🦉", "slovak": "sova", "pronunciation": "SOH-vah",
        "english": "owl",
        "example_sk": "Sova poľná loví myši na podtatranských lúkach v noci.",
        "example_en": "The barn owl hunts mice in the sub-Tatra meadows at night.",
        "rarity": "common", "number": 5, "origin": "Pan-Slavic",
    },
    {
        "id": 96, "set_id": "zvierata", "set_name": "Tatranská Fauna", "set_emoji": "🐻",
        "emoji": "🐿️", "slovak": "veverička", "pronunciation": "VEH-veh-rich-kah",
        "english": "squirrel",
        "example_sk": "Veverička skáče z vetvy na vetvu v tatranskom lese.",
        "example_en": "The squirrel jumps from branch to branch in the Tatra forest.",
        "rarity": "common", "number": 6, "origin": "Pan-Slavic",
    },
    {
        "id": 97, "set_id": "zvierata", "set_name": "Tatranská Fauna", "set_emoji": "🐻",
        "emoji": "🦢", "slovak": "bocian", "pronunciation": "BOH-tsyahn",
        "english": "stork",
        "example_sk": "Bocian si stavia hniezdo na komíne starých domov na východnom Slovensku.",
        "example_en": "The stork builds its nest on chimneys of old houses in eastern Slovakia.",
        "rarity": "common", "number": 7, "origin": "Pan-Slavic",
    },
    {
        "id": 98, "set_id": "zvierata", "set_name": "Tatranská Fauna", "set_emoji": "🐻",
        "emoji": "🦅", "slovak": "orol", "pronunciation": "OH-rol",
        "english": "eagle",
        "example_sk": "Orol skalný krúži vysoko nad tatranskými štítmi.",
        "example_en": "The golden eagle circles high above the Tatra peaks.",
        "rarity": "common", "number": 8, "origin": "Pan-Slavic",
    },
    {
        "id": 99, "set_id": "zvierata", "set_name": "Tatranská Fauna", "set_emoji": "🐻",
        "emoji": "🐱", "slovak": "rys", "pronunciation": "RIHS",
        "english": "lynx",
        "example_sk": "Rys ostrovid je plachý a žije v odľahlých slovenských horách.",
        "example_en": "The Eurasian lynx is shy and lives in remote Slovak mountains.",
        "rarity": "uncommon", "number": 9, "origin": "Pan-Slavic",
    },
    {
        "id": 100, "set_id": "zvierata", "set_name": "Tatranská Fauna", "set_emoji": "🐻",
        "emoji": "🐐", "slovak": "kamzík", "pronunciation": "KAHM-zeek",
        "english": "chamois",
        "example_sk": "Kamzík sa šplhá po strmých skalách vo Vysokých Tatrách.",
        "example_en": "The chamois climbs steep rocks in the High Tatras.",
        "rarity": "uncommon", "number": 10, "origin": "Slovak",
    },
    {
        "id": 101, "set_id": "zvierata", "set_name": "Tatranská Fauna", "set_emoji": "🐻",
        "emoji": "🐓", "slovak": "tetrov", "pronunciation": "TET-rov",
        "english": "grouse",
        "example_sk": "Tetrov hlucháň je vzácny vták slovenských horských lesov.",
        "example_en": "The capercaillie is a rare bird of Slovak mountain forests.",
        "rarity": "uncommon", "number": 11, "origin": "Pan-Slavic",
    },
    {
        "id": 102, "set_id": "zvierata", "set_name": "Tatranská Fauna", "set_emoji": "🐻",
        "emoji": "🦡", "slovak": "kuna", "pronunciation": "KOO-nah",
        "english": "marten",
        "example_sk": "Kuna lesná je rýchly a obratný predátor slovenských lesov.",
        "example_en": "The pine marten is a fast and agile predator of Slovak forests.",
        "rarity": "uncommon", "number": 12, "origin": "Pan-Slavic",
    },
    {
        "id": 103, "set_id": "zvierata", "set_name": "Tatranská Fauna", "set_emoji": "🐻",
        "emoji": "🦬", "slovak": "zubor", "pronunciation": "ZOO-bor",
        "english": "wisent / European bison",
        "example_sk": "Zubor je najväčšie suchozemské zviera v Európe a žije aj na Slovensku.",
        "example_en": "The European bison is the largest land animal in Europe and also lives in Slovakia.",
        "rarity": "rare", "number": 13, "origin": "Pan-Slavic",
    },
    {
        "id": 104, "set_id": "zvierata", "set_name": "Tatranská Fauna", "set_emoji": "🐻",
        "emoji": "🦉", "slovak": "výr skalný", "pronunciation": "VEER SKAHL-nee",
        "english": "eagle-owl",
        "example_sk": "Výr skalný je najväčšia sova v Európe a hniezdi aj v slovenských skalách.",
        "example_en": "The eagle-owl is the largest owl in Europe and nests in Slovak cliffs.",
        "rarity": "rare", "number": 14, "origin": "Pan-Slavic",
    },
    {
        "id": 105, "set_id": "zvierata", "set_name": "Tatranská Fauna", "set_emoji": "🐻",
        "emoji": "🏔️", "slovak": "kamzík vrchovský tatranský", "pronunciation": "KAHM-zeek VUR-khov-skee TAH-trahn-skee",
        "english": "Tatra chamois (unique species)",
        "example_sk": "Kamzík vrchovský tatranský je unikátny druh a symbol Tatier aj piva Tatran.",
        "example_en": "The Tatra chamois is a unique species and a symbol of the Tatras and Tatran beer.",
        "rarity": "legendary", "number": 15, "origin": "Slovak",
    },

    # =========================================================================
    # SET 8: Tradície (Traditions) 🎭
    # 8 Common, 4 Uncommon, 2 Rare, 1 Legendary
    # =========================================================================
    {
        "id": 106, "set_id": "tradicie", "set_name": "Tradície", "set_emoji": "🎭",
        "emoji": "🎄", "slovak": "Vianoce", "pronunciation": "VYAH-noh-tseh",
        "english": "Christmas",
        "example_sk": "Na Vianoce sa celá rodina stretáva pri štedrej večeri.",
        "example_en": "At Christmas the whole family gathers for the Christmas Eve dinner.",
        "rarity": "common", "number": 1, "origin": "Pan-Slavic",
    },
    {
        "id": 107, "set_id": "tradicie", "set_name": "Tradície", "set_emoji": "🎭",
        "emoji": "🐣", "slovak": "Veľká noc", "pronunciation": "VEL-kah NOTS",
        "english": "Easter",
        "example_sk": "Veľká noc je na Slovensku spojená s mnohými ľudovými tradíciami.",
        "example_en": "Easter in Slovakia is connected with many folk traditions.",
        "rarity": "common", "number": 2, "origin": "Pan-Slavic",
    },
    {
        "id": 108, "set_id": "tradicie", "set_name": "Tradície", "set_emoji": "🎭",
        "emoji": "🎭", "slovak": "fašiangy", "pronunciation": "FAH-shyahn-gih",
        "english": "Carnival",
        "example_sk": "Počas fašiangov sa ľudia obliekajú do masiek a tancujú.",
        "example_en": "During Carnival people dress up in costumes and dance.",
        "rarity": "common", "number": 3, "origin": "International",
    },
    {
        "id": 109, "set_id": "tradicie", "set_name": "Tradície", "set_emoji": "🎭",
        "emoji": "💒", "slovak": "svadba", "pronunciation": "SVAHD-bah",
        "english": "wedding",
        "example_sk": "Slovenská svadba trvá tradične dva až tri dni.",
        "example_en": "A Slovak wedding traditionally lasts two to three days.",
        "rarity": "common", "number": 4, "origin": "Pan-Slavic",
    },
    {
        "id": 110, "set_id": "tradicie", "set_name": "Tradície", "set_emoji": "🎭",
        "emoji": "👶", "slovak": "krstiny", "pronunciation": "KURS-tyih-nih",
        "english": "christening / baptism",
        "example_sk": "Na krstinách sa dieťa dostane krstného otca a krstnú mamu.",
        "example_en": "At the christening the child gets a godfather and a godmother.",
        "rarity": "common", "number": 5, "origin": "Pan-Slavic",
    },
    {
        "id": 111, "set_id": "tradicie", "set_name": "Tradície", "set_emoji": "🎭",
        "emoji": "💃", "slovak": "ples", "pronunciation": "PLES",
        "english": "ball / dance",
        "example_sk": "Každú zimu sa na Slovensku konajú stužkové plesy maturantov.",
        "example_en": "Every winter, graduation ribbon balls are held in Slovakia.",
        "rarity": "common", "number": 6, "origin": "International",
    },
    {
        "id": 112, "set_id": "tradicie", "set_name": "Tradície", "set_emoji": "🎭",
        "emoji": "🕯️", "slovak": "sviečka", "pronunciation": "SVYECH-kah",
        "english": "candle",
        "example_sk": "Na Dušičky sa zapaľujú sviečky na hroboch zosnulých.",
        "example_en": "On All Souls' Day candles are lit on the graves of the deceased.",
        "rarity": "common", "number": 7, "origin": "Pan-Slavic",
    },
    {
        "id": 113, "set_id": "tradicie", "set_name": "Tradície", "set_emoji": "🎭",
        "emoji": "🔔", "slovak": "zvon", "pronunciation": "ZVON",
        "english": "bell",
        "example_sk": "Zvony kostola zvoňia každú nedeľu ráno v dedinách po celom Slovensku.",
        "example_en": "Church bells ring every Sunday morning in villages across Slovakia.",
        "rarity": "common", "number": 8, "origin": "Pan-Slavic",
    },
    {
        "id": 114, "set_id": "tradicie", "set_name": "Tradície", "set_emoji": "🎭",
        "emoji": "🌊", "slovak": "Morena", "pronunciation": "MOH-reh-nah",
        "english": "drowning of Morena (winter effigy)",
        "example_sk": "Na jar dievčatá vynášajú Morenu a hádžu ju do vody na rozlúčku so zimou.",
        "example_en": "In spring, girls carry out Morena and throw her into the water to bid farewell to winter.",
        "rarity": "uncommon", "number": 9, "origin": "Pan-Slavic",
    },
    {
        "id": 115, "set_id": "tradicie", "set_name": "Tradície", "set_emoji": "🎭",
        "emoji": "💦", "slovak": "oblievačka", "pronunciation": "OB-lyeh-vach-kah",
        "english": "Easter water pouring",
        "example_sk": "Na Veľkú noc chlapci oblievajú dievčatá studenou vodou.",
        "example_en": "At Easter boys pour cold water on girls to keep them fresh and healthy.",
        "rarity": "uncommon", "number": 10, "origin": "Slovak",
    },
    {
        "id": 116, "set_id": "tradicie", "set_name": "Tradície", "set_emoji": "🎭",
        "emoji": "🪢", "slovak": "šibačka", "pronunciation": "SHIH-bahch-kah",
        "english": "Easter whipping",
        "example_sk": "Šibačka je veľkonočný zvyk, pri ktorom chlapci šibú dievčatá korbáčom.",
        "example_en": "Easter whipping is a tradition where boys gently whip girls with a braided willow switch.",
        "rarity": "uncommon", "number": 11, "origin": "Slovak",
    },
    {
        "id": 117, "set_id": "tradicie", "set_name": "Tradície", "set_emoji": "🎭",
        "emoji": "🍞", "slovak": "vianočka", "pronunciation": "VYAH-noch-kah",
        "english": "Christmas bread",
        "example_sk": "Vianočka je pletený vianočný koláč, ktorý sa pečie v každej rodine.",
        "example_en": "Vianocka is a braided Christmas bread baked in every family.",
        "rarity": "uncommon", "number": 12, "origin": "Slovak",
    },
    {
        "id": 118, "set_id": "tradicie", "set_name": "Tradície", "set_emoji": "🎭",
        "emoji": "🎶", "slovak": "fujara", "pronunciation": "FOO-yah-rah",
        "english": "giant folk flute (UNESCO heritage)",
        "example_sk": "Fujara je veľká pastierska flauta zapísaná v zozname UNESCO.",
        "example_en": "The fujara is a large shepherd's flute listed on the UNESCO heritage list.",
        "rarity": "rare", "number": 13, "origin": "Slovak",
    },
    {
        "id": 119, "set_id": "tradicie", "set_name": "Tradície", "set_emoji": "🎭",
        "emoji": "🏘️", "slovak": "Čičmany", "pronunciation": "CHICH-mah-nih",
        "english": "Cicmany (village with painted houses)",
        "example_sk": "Domy v Čičmanoch sú zdobené bielymi ornamentmi, ktoré sú symbolom Slovenska.",
        "example_en": "Houses in Cicmany are decorated with white ornaments that are a symbol of Slovakia.",
        "rarity": "rare", "number": 14, "origin": "Slovak",
    },
    {
        "id": 120, "set_id": "tradicie", "set_name": "Tradície", "set_emoji": "🎭",
        "emoji": "👗", "slovak": "kroj", "pronunciation": "KROY",
        "english": "traditional folk costume",
        "example_sk": "Kroj reprezentuje celú slovenskú ľudovú kultúru a každý región má svoj vlastný.",
        "example_en": "The folk costume represents all of Slovak folk culture and every region has its own.",
        "rarity": "legendary", "number": 15, "origin": "Slovak",
    },

    # =========================================================================
    # SET 9: Slovenská Príroda (Slovak Nature) 🏔️
    # 8 Common, 4 Uncommon, 2 Rare, 1 Legendary
    # =========================================================================
    {
        "id": 121, "set_id": "priroda", "set_name": "Slovenská Príroda", "set_emoji": "🏔️",
        "emoji": "🌲", "slovak": "les", "pronunciation": "LES",
        "english": "forest",
        "example_sk": "Slovenské lesy pokrývajú viac ako štyridať percent krajiny.",
        "example_en": "Slovak forests cover more than forty percent of the country.",
        "rarity": "common", "number": 1, "origin": "Pan-Slavic",
    },
    {
        "id": 122, "set_id": "priroda", "set_name": "Slovenská Príroda", "set_emoji": "🏔️",
        "emoji": "🌊", "slovak": "rieka", "pronunciation": "RYEH-kah",
        "english": "river",
        "example_sk": "Váh je najdlhšia rieka, ktorá tečie celým Slovenskom.",
        "example_en": "The Vah is the longest river that flows through all of Slovakia.",
        "rarity": "common", "number": 2, "origin": "Pan-Slavic",
    },
    {
        "id": 123, "set_id": "priroda", "set_name": "Slovenská Príroda", "set_emoji": "🏔️",
        "emoji": "⛰️", "slovak": "hora", "pronunciation": "HOH-rah",
        "english": "mountain",
        "example_sk": "Slovensko je hornatá krajina s nádhernými výhľadmi.",
        "example_en": "Slovakia is a mountainous country with stunning views.",
        "rarity": "common", "number": 3, "origin": "Pan-Slavic",
    },
    {
        "id": 124, "set_id": "priroda", "set_name": "Slovenská Príroda", "set_emoji": "🏔️",
        "emoji": "🏞️", "slovak": "jazero", "pronunciation": "YAH-zeh-roh",
        "english": "lake",
        "example_sk": "Na Slovensku je množstvo prírodných jazier aj umelých priehrad.",
        "example_en": "Slovakia has many natural lakes and man-made reservoirs.",
        "rarity": "common", "number": 4, "origin": "Pan-Slavic",
    },
    {
        "id": 125, "set_id": "priroda", "set_name": "Slovenská Príroda", "set_emoji": "🏔️",
        "emoji": "🌿", "slovak": "lúka", "pronunciation": "LOO-kah",
        "english": "meadow",
        "example_sk": "Na podtatranských lúkach rastú vzácne horské kvety.",
        "example_en": "Rare mountain flowers grow in the sub-Tatra meadows.",
        "rarity": "common", "number": 5, "origin": "Pan-Slavic",
    },
    {
        "id": 126, "set_id": "priroda", "set_name": "Slovenská Príroda", "set_emoji": "🏔️",
        "emoji": "🏔️", "slovak": "dolina", "pronunciation": "DOH-lih-nah",
        "english": "valley",
        "example_sk": "Demänovská dolina je jedna z najkrajších dolín na Slovensku.",
        "example_en": "Demanovska Valley is one of the most beautiful valleys in Slovakia.",
        "rarity": "common", "number": 6, "origin": "Pan-Slavic",
    },
    {
        "id": 127, "set_id": "priroda", "set_name": "Slovenská Príroda", "set_emoji": "🏔️",
        "emoji": "🌀", "slovak": "potok", "pronunciation": "POH-tok",
        "english": "stream",
        "example_sk": "Horský potok zurčí cez kamene v hlbokej doline.",
        "example_en": "The mountain stream babbles over stones in the deep valley.",
        "rarity": "common", "number": 7, "origin": "Pan-Slavic",
    },
    {
        "id": 128, "set_id": "priroda", "set_name": "Slovenská Príroda", "set_emoji": "🏔️",
        "emoji": "🪨", "slovak": "skala", "pronunciation": "SKAH-lah",
        "english": "rock",
        "example_sk": "Na vrchole skaly bol nádherný výhľad na celú dolinu.",
        "example_en": "At the top of the rock there was a magnificent view of the whole valley.",
        "rarity": "common", "number": 8, "origin": "Pan-Slavic",
    },
    {
        "id": 129, "set_id": "priroda", "set_name": "Slovenská Príroda", "set_emoji": "🏔️",
        "emoji": "🏔️", "slovak": "Vysoké Tatry", "pronunciation": "VIH-soh-keh TAH-trih",
        "english": "High Tatras",
        "example_sk": "Vysoké Tatry sú najmenšie veľhory na svete.",
        "example_en": "The High Tatras are the smallest high mountains in the world.",
        "rarity": "uncommon", "number": 9, "origin": "Slovak",
    },
    {
        "id": 130, "set_id": "priroda", "set_name": "Slovenská Príroda", "set_emoji": "🏔️",
        "emoji": "🌄", "slovak": "Slovenský raj", "pronunciation": "SLOH-ven-skee RAI",
        "english": "Slovak Paradise (national park)",
        "example_sk": "Slovenský raj je plný rebríkov, mostíkov a vodopádov v hlbokých roklinách.",
        "example_en": "Slovak Paradise is full of ladders, bridges, and waterfalls in deep gorges.",
        "rarity": "uncommon", "number": 10, "origin": "Slovak",
    },
    {
        "id": 131, "set_id": "priroda", "set_name": "Slovenská Príroda", "set_emoji": "🏔️",
        "emoji": "🛶", "slovak": "Dunajec", "pronunciation": "DOO-nah-yets",
        "english": "Dunajec river gorge",
        "example_sk": "Splav Dunajca na pltiach je jedinečný zážitok na hranici s Poľskom.",
        "example_en": "Rafting down the Dunajec on wooden rafts is a unique experience on the Polish border.",
        "rarity": "uncommon", "number": 11, "origin": "Slovak",
    },
    {
        "id": 132, "set_id": "priroda", "set_name": "Slovenská Príroda", "set_emoji": "🏔️",
        "emoji": "🧊", "slovak": "Dobšinská jaskyňa", "pronunciation": "DOB-shin-skah YAHS-kih-nyah",
        "english": "Dobsinska Ice Cave",
        "example_sk": "Dobšinská ľadová jaskyňa je zapísaná v UNESCO a ľad v nej nikdy neroztopí.",
        "example_en": "Dobsinska Ice Cave is a UNESCO site and the ice inside never melts.",
        "rarity": "uncommon", "number": 12, "origin": "Slovak",
    },
    {
        "id": 133, "set_id": "priroda", "set_name": "Slovenská Príroda", "set_emoji": "🏔️",
        "emoji": "🕳️", "slovak": "priepasť", "pronunciation": "PRYEH-pahsty",
        "english": "abyss / chasm",
        "example_sk": "V slovenských horách sa nachádzajú hlboké priepasti v krasových oblastiach.",
        "example_en": "Deep abysses are found in the karst regions of the Slovak mountains.",
        "rarity": "rare", "number": 13, "origin": "Pan-Slavic",
    },
    {
        "id": 134, "set_id": "priroda", "set_name": "Slovenská Príroda", "set_emoji": "🏔️",
        "emoji": "💎", "slovak": "pleso", "pronunciation": "PLEH-soh",
        "english": "mountain lake (Tatra word)",
        "example_sk": "Vo Vysokých Tatrách je viac ako sto horských plies ľadovcového pôvodu.",
        "example_en": "In the High Tatras there are more than a hundred glacial mountain lakes called plesa.",
        "rarity": "rare", "number": 14, "origin": "Slovak",
    },
    {
        "id": 135, "set_id": "priroda", "set_name": "Slovenská Príroda", "set_emoji": "🏔️",
        "emoji": "🇸🇰", "slovak": "Kriváň", "pronunciation": "KRIH-vahn",
        "english": "Krivan (iconic Slovak mountain peak)",
        "example_sk": "Kriváň je symbolom Slovenska a je vyobrazený na slovenských eurových minciach.",
        "example_en": "Krivan is a symbol of Slovakia and is depicted on Slovak euro coins.",
        "rarity": "legendary", "number": 15, "origin": "Slovak",
    },

    # =========================================================================
    # SET 10: Hudba a Umenie (Music & Art) 🎵
    # 8 Common, 4 Uncommon, 2 Rare, 1 Legendary
    # =========================================================================
    {
        "id": 136, "set_id": "hudba", "set_name": "Hudba a Umenie", "set_emoji": "🎵",
        "emoji": "🎵", "slovak": "pieseň", "pronunciation": "PYEH-sen",
        "english": "song",
        "example_sk": "Slovenské ľudové piesne sú plné krásy a melanchólie.",
        "example_en": "Slovak folk songs are full of beauty and melancholy.",
        "rarity": "common", "number": 1, "origin": "Pan-Slavic",
    },
    {
        "id": 137, "set_id": "hudba", "set_name": "Hudba a Umenie", "set_emoji": "🎵",
        "emoji": "💃", "slovak": "tanec", "pronunciation": "TAH-nets",
        "english": "dance",
        "example_sk": "Slovenský ľudový tanec je plný energie a radosti.",
        "example_en": "Slovak folk dance is full of energy and joy.",
        "rarity": "common", "number": 2, "origin": "Pan-Slavic",
    },
    {
        "id": 138, "set_id": "hudba", "set_name": "Hudba a Umenie", "set_emoji": "🎵",
        "emoji": "🎻", "slovak": "husle", "pronunciation": "HOOS-leh",
        "english": "violin",
        "example_sk": "Husle sú hlavný nástroj v slovenskej ľudovej hudbe.",
        "example_en": "The violin is the main instrument in Slovak folk music.",
        "rarity": "common", "number": 3, "origin": "Pan-Slavic",
    },
    {
        "id": 139, "set_id": "hudba", "set_name": "Hudba a Umenie", "set_emoji": "🎵",
        "emoji": "🥁", "slovak": "bubon", "pronunciation": "BOO-bon",
        "english": "drum",
        "example_sk": "Bubon udáva rytmus pri ľudových tancoch.",
        "example_en": "The drum sets the rhythm for folk dances.",
        "rarity": "common", "number": 4, "origin": "Pan-Slavic",
    },
    {
        "id": 140, "set_id": "hudba", "set_name": "Hudba a Umenie", "set_emoji": "🎵",
        "emoji": "🎤", "slovak": "spev", "pronunciation": "SPEV",
        "english": "singing",
        "example_sk": "Spoločný spev pri ohni je tradíciou slovenských táborákov.",
        "example_en": "Singing together by the fire is a tradition at Slovak campfires.",
        "rarity": "common", "number": 5, "origin": "Pan-Slavic",
    },
    {
        "id": 141, "set_id": "hudba", "set_name": "Hudba a Umenie", "set_emoji": "🎵",
        "emoji": "🎼", "slovak": "harmónia", "pronunciation": "HAR-moh-nyah",
        "english": "harmony",
        "example_sk": "Harmónia hlasov v slovenskom zbore znie nádherné.",
        "example_en": "The harmony of voices in a Slovak choir sounds magnificent.",
        "rarity": "common", "number": 6, "origin": "International",
    },
    {
        "id": 142, "set_id": "hudba", "set_name": "Hudba a Umenie", "set_emoji": "🎵",
        "emoji": "🎶", "slovak": "melódia", "pronunciation": "MEH-loh-dyah",
        "english": "melody",
        "example_sk": "Melódia tejto ľudovej piesne mi pripomína detstvo.",
        "example_en": "The melody of this folk song reminds me of childhood.",
        "rarity": "common", "number": 7, "origin": "International",
    },
    {
        "id": 143, "set_id": "hudba", "set_name": "Hudba a Umenie", "set_emoji": "🎵",
        "emoji": "🔊", "slovak": "rytmus", "pronunciation": "RIT-mus",
        "english": "rhythm",
        "example_sk": "Rytmus slovenských ľudoviek je živý a tanečný.",
        "example_en": "The rhythm of Slovak folk music is lively and danceable.",
        "rarity": "common", "number": 8, "origin": "International",
    },
    {
        "id": 144, "set_id": "hudba", "set_name": "Hudba a Umenie", "set_emoji": "🎵",
        "emoji": "🎹", "slovak": "cimbal", "pronunciation": "TSIM-bahl",
        "english": "dulcimer / hammered strings",
        "example_sk": "Cimbal je typický nástroj ľudových hudieb na Slovensku.",
        "example_en": "The dulcimer is a typical instrument of folk bands in Slovakia.",
        "rarity": "uncommon", "number": 9, "origin": "Hungarian influence",
    },
    {
        "id": 145, "set_id": "hudba", "set_name": "Hudba a Umenie", "set_emoji": "🎵",
        "emoji": "🎺", "slovak": "gajdy", "pronunciation": "GAI-dih",
        "english": "bagpipes",
        "example_sk": "Gajdy sa hrávali na slovenských svadbách a pastierskych slávnostiach.",
        "example_en": "Bagpipes were played at Slovak weddings and shepherd festivals.",
        "rarity": "uncommon", "number": 10, "origin": "Pan-Slavic",
    },
    {
        "id": 146, "set_id": "hudba", "set_name": "Hudba a Umenie", "set_emoji": "🎵",
        "emoji": "🪈", "slovak": "fujara", "pronunciation": "FOO-yah-rah",
        "english": "folk flute",
        "example_sk": "Zvuk fujary sa nesie cez tatranské doliny ako hlas pastierov.",
        "example_en": "The sound of the fujara carries across Tatra valleys like the voice of shepherds.",
        "rarity": "uncommon", "number": 11, "origin": "Slovak",
    },
    {
        "id": 147, "set_id": "hudba", "set_name": "Hudba a Umenie", "set_emoji": "🎵",
        "emoji": "🎵", "slovak": "ľudová pieseň", "pronunciation": "LYOO-doh-vah PYEH-sen",
        "english": "folk song",
        "example_sk": "Ľudové piesne sa na Slovensku dedia z generácie na generáciu.",
        "example_en": "Folk songs in Slovakia are passed down from generation to generation.",
        "rarity": "uncommon", "number": 12, "origin": "Pan-Slavic",
    },
    {
        "id": 148, "set_id": "hudba", "set_name": "Hudba a Umenie", "set_emoji": "🎵",
        "emoji": "🔷", "slovak": "čičmanský vzor", "pronunciation": "CHICH-mahn-skee VZOR",
        "english": "Cicmany pattern (geometric folk art)",
        "example_sk": "Čičmanský vzor sa stal ikonickým symbolom slovenského dizajnu.",
        "example_en": "The Cicmany pattern has become an iconic symbol of Slovak design.",
        "rarity": "rare", "number": 13, "origin": "Slovak",
    },
    {
        "id": 149, "set_id": "hudba", "set_name": "Hudba a Umenie", "set_emoji": "🎵",
        "emoji": "🏺", "slovak": "modranská keramika", "pronunciation": "MOD-rahn-skah KEH-rah-mih-kah",
        "english": "Modra ceramics",
        "example_sk": "Modranská keramika je tradičné ručne maľované hrnčiarstvo z mesta Modra.",
        "example_en": "Modra ceramics is traditional hand-painted pottery from the town of Modra.",
        "rarity": "rare", "number": 14, "origin": "Slovak",
    },
    {
        "id": 150, "set_id": "hudba", "set_name": "Hudba a Umenie", "set_emoji": "🎵",
        "emoji": "🌟", "slovak": "Lúčnica", "pronunciation": "LOO-chnih-tsah",
        "english": "Lucnica (legendary folk dance ensemble)",
        "example_sk": "Lúčnica je svetoznámy slovenský folklórny súbor, ktorý vystupuje po celom svete.",
        "example_en": "Lucnica is a world-famous Slovak folk ensemble that performs all around the world.",
        "rarity": "legendary", "number": 15, "origin": "Slovak",
    },
]

# Index by ID for fast lookup
CARD_BY_ID: dict[int, CardDef] = {c["id"]: c for c in CARDS}

# Index by set
CARDS_BY_SET: dict[str, list[CardDef]] = {}
for c in CARDS:
    CARDS_BY_SET.setdefault(c["set_id"], []).append(c)
